# Generated by Django 4.1.7 on 2025-02-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='dexterity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='character',
            name='endurance',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='character',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='luck',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='character',
            name='strength',
            field=models.IntegerField(default=1),
        ),
    ]
