# Generated by Django 4.1.7 on 2025-02-03 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_character_dexterity_character_endurance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='max_health',
        ),
    ]
