# Generated by Django 4.1.7 on 2025-02-03 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_remove_character_max_health'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='max_health',
            field=models.IntegerField(default=100),
        ),
    ]
