# Generated by Django 4.1.7 on 2025-02-03 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_character_max_health'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='skill_points',
            field=models.IntegerField(default=0),
        ),
    ]
