# Generated by Django 4.1.7 on 2025-02-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0005_character_skill_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='photo',
            field=models.ImageField(blank=True, default='images/default.png', null=True, upload_to='characters/'),
        ),
    ]
